### PR TITLE
Error System

### PR DESCRIPTION
**Pull request by Andy-Python-Programmer**
This pull updates the error system to make the errors look nicer! Also will contain warnings in future. This pull is WIP ( Work In Progress )

### CODE REVIEW

**Comment by Calamity210** [comment]
Does this need a review yet?

**Comment by Andy-Python-Programmer** [comment]
> Does this need a review yet?

Yes

**Comment by Calamity210** [comment]
@Andy-Python-Programmer can you update the tests for this?

**Comment by Calamity210** [comment]
Closing as its been worked on in e9a6014

**Pull request closed without merging**
